dist: trusty

language: generic

php:
    - '5.6'
    - '7.1'

node_js:
  - node

jobs:
    include:
        - name: PHPunit tests (single, 7.1)
          php: '7.1'
          env: WP_VERSION=latest WP_MULTISITE=0
          before_install:
            - phpenv global 7.1
            - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
          script:
            - phpunit

        - name: PHPunit tests (multi, 7.1)
          php: '7.1'
          env: WP_VERSION=latest WP_MULTISITE=1
          before_install:
            - phpenv global 7.1
            - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
          script:
            - phpunit

        - name: PHPunit tests (single, 5.6)
          php: '5.6'
          env: WP_VERSION=latest WP_MULTISITE=0
          before_install:
            - phpenv global 5.6
            - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
          script:
            - phpunit

        - name: Jest tests
          before_install:
            - nvm install 12.14.0
            - nvm use 12.14.0
            - yarn install --ignore-engines
          script:
            - yarn test
